### PR TITLE
avoid "fatal state" error in supervisord and add automatic install and configuration file

### PR DESCRIPTION
**Pull request by Potomac**
fix errors messages in supervisord related to checkstart process

### CODE REVIEW

**Comment by Potomac** [comment]
this pull request has bug, please correct the startsecs option like this : 

```
[program:checkstart]
command=/usr/local/bin/ojs-pre-start
startsecs=1
exitcodes=0
```

**Comment by Potomac** [comment]
here is a new pull request which add automatic installation (no need anymore of OJS_CLI_INSTALL), and add automatic recreation of config.inc.php file (no need anymore to use volume for storing config.inc.php, this file will be recreated on the fly by using docker environment variables and sed commands in recreate_config script)

**Comment by lucasdiedrich** [comment]
Hey @Potomac , you should use one PR peer new feature, what i'm seeing is that you're using an old version of the branch, which has the atributes poiting to **/var/www/html/files** instead of **/var/www/files**. Can't merge like this, first pull the latest version, second make a PR with separates new features, one for fixing the supervisor, and another with the handle of config.inc.php.

Thanks a lot for your help.

**Comment by Potomac** [comment]
@lucasdiedrich : I fixed the wrong path for upload dir,

for the fixing of supervisor I think my fix doesn't really work, sometimes I get the message "fatal state" for checkstart,

I think the main problem is the fact that supervisor is not suitable for running startup script, it is designed to run daemons, so a better solution is to run ojs-pre-start script with something like systemd (but alpine linux uses a different init software)

**Comment by Potomac** [comment]
A cron script may be work for launching once at boot ojs-pre-start ?

**Comment by marcbria** [comment]
Hi all,
I saw plenty of changes on those PRs... and I agree with some but I disagree with others.

We need to keep this work as generic as possible to be useful for developers, testers and sysops... so we need to avoid thinking in just our local scenario.

@Potomac, do you mind to make a PR for each specific change so we can talk about them separately?

Thanks for your work,
m.

**Pull request closed without merging**
