### PR TITLE
Some commented proposals to discuss and improve docker-compose.

### PR DESCRIPTION
**Pull request by marcbria**
Hi Lucas,
First, thanks a lot for the great work done with this.
Your initial work was good but now is even better.
Congratulations for your 10K downloads. ;-)

This pull request are some proposals that I think could improve your docker-compose.
Do you like to discuss them?

BTW, Are you planing to add tags synchronized with PKP's versions?
I mean... I see you have a PR to move to 3.1.1-4, but a tag also need to be created to let people refer the right version, isn't it?

Once we finish with this, what about talking about an official Dockerfile for pkp?

Thanks again,
m.

### CODE REVIEW

**Comment by lucasdiedrich** [comment]
Hey @marcbria, awesome suggestions, going to merge this as soon as possible. 

About the 3.1.1-4 tag i really forgot to made that as this is kind manual thing to do. going to fix this too.

Thanks.

**Comment by marcbria** [comment]
Hi Lucas... not to hurry you, but would be wonderful start testing 3.1.1-4 version.
I see it's changed in master but not as tags.
Any schedule about this change?

BTW, I have seen the repo was pulled 50K so congrats again. You did a great work.

Today we have a PKP tech meeting. Do you have enough time and interest to keep the official pkp dockers? If you like I can propose your name today or in the next meeting.

Thanks for your time,
m.

**Comment by lucasdiedrich** [comment]
Going to do that as soon as possible marc, probably tomorrow, sorry for
that.

About the official pkp dockers, if i would be in charge i would have to
manage to get free time for the project without a problem, so you can
propose, i'm happy to help you guys.

Thanks!!


Em qui, 21 de fev de 2019 às 12:56, Marc Bria <notifications@github.com>
escreveu:

**Comment by lucasdiedrich** [comment]
@marcbria , quick update, i created the new release tag here at github. Force the building process for master branch at dockerhub. 

For some reason Dockerhub is not detecting the new tag (3.1.1-4). I think it should get some time to make that. Anyway later i'll look again.

Thanks

**Comment by lucasdiedrich** [comment]
@marcbria , as promised i was able to construct the new tag (3.1.1-4) container, i had to rebuild the auto-build configuration over dockerhub. Sorry for taking so long.

Thanks.

**Comment by marcbria** [comment]
Thanks a lot for thet tag. Testing it right now ;-)

> About the official pkp dockers, if i would be in charge i would have to manage to get free time for the project without a problem, so you can propose, i'm happy to help you guys.

Good news. Thanks.
I will talk with tech committee and I will be back with a proposal.

In fact, at the beginning I was just thinking in including you in the "new release" workflows to let you update the tags and check if the docker image is still working, but I recognize I'm not sure about what "official" means for dockerhub in terms of additional work. :-)

They talk about this here but reading this I still have doubts:
https://docs.docker.com/docker-hub/official_images/
Do you know what what else need to be done to keep an official image?

**Pull request merged**
